[package]
name = "kev-project0"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "1.2.1"
keos = { path ="../../keos" }

[dependencies.iced-x86]
version = "1.18.0"
default-features = false
features = ["no_std", "decoder", "intel"]
